name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Install LFTP
      run: sudo apt-get install -y lftp

    - name: Sync files via LFTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER_PROD }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME_PROD }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD_PROD }}
      run: |
        lftp -c "
        debug 5;
        set ftp:ssl-allow yes;
        set ftp:ssl-force true;
        set ftp:ssl-auth TLS;
        set ftp:ssl-protect-data true;
        set ssl:verify-certificate no;
        open -u \"$FTP_USERNAME\",\"$FTP_PASSWORD\" -p 21 \"$FTP_SERVER\";
        mirror -R -v --parallel=2 --exclude-glob .git* --exclude-glob .git/ --exclude-glob node_modules/ --exclude-glob .github/ ./ /web;
        quit
        "
